### ISSUE TITLE
Display important information of a single product

### ISSUE THREAD

**Issue by aclaes** [aclaes/capstone-project#1]
# Value Proposition

**As a** shop administrator
**I want to** see the details of a product
**So that** I can verify the data of the product

# Description

![Image](https://user-images.githubusercontent.com/7231474/184125368-3d8f2970-defa-429e-a3a2-cc7c8a99654f.png)

# Acceptance Criteria

- [x] The product's name is displayed
- [x] The product's description is displayed
- [x] The product's price is displayed

# Tasks

- [x] Create a new Feature Branch
- [x]  Create constant holding the data structure for a single product
- [ ] Create a compontent that receives a product's data via props and renders it
- [ ] Add a test to check if the component renders the correct data
- [ ] Add basic styling to distinguish between headline and dynamic content
- [ ] Add to Storybook

# Complexity

M
