### ISSUE TITLE
Create a new product

### ISSUE THREAD

**Issue by aclaes** [aclaes/capstone-project#2]
# Value Proposition

**As a** shop administrator
**I want to** add a new product to the shop
**So that** I can increase the variety of products for our customers.

# Description

![Image](https://user-images.githubusercontent.com/7231474/184130272-c16e8238-a423-415b-b471-ecdbdc934de5.png)

# Acceptance Criteria

- [ ] An input field for the product's name is displayed (label: "Name")
- [ ] An input field for the product's description is displayed  (label: "Description")
- [ ] An input field for the product's price is displayed  (label: "Price in EUR")
- [ ] A submit button is displayed
- [ ] All three form fields are required
- [ ] The price must be an positive integer
- [ ] After submitting the form the new product is displayed in the list of all products

# Tasks

- [ ] Create a form component with three input fields 
- [ ] Add a submit button to the form
- [ ] Add  `event.preventDefault()` to the form submit
- [ ] Create form validation
- [ ] Write tests to check the form validation
- [ ] Write tests to check if the product was added to the list
- [ ] Add state handling (with zustand.js)

# Complexity

XL
